version: '3.8'

services: 
  mysqldb:
    hostname: mysql.example.com
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - $MYSQL_LOCAL_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
      - ./db-dump/testdump.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      - turingmysql

  app:
    hostname: node.example.com 
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sangram/apistack
    ports:
      - 3001:3000
    expose:
      - 3001
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    networks:
      - turingmysql

volumes: 
  db-config:
  db-data:

networks:
  turingmysql:
    driver: bridge  
